#!/bin/sh
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home
jsvc -cp commons-daemon.jar:~/bin/clojure.jar:target/cljsvc-0.0.1-standalone.jar \
  -cwd ~justin/sprinklr/cljsvc \
  -outfile cljsvc.out \
  -errfile cljsvc.err \
  org.noisesmith.Cljsvc
